version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
      - image: postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: build_balance
          POSTGRES_PASSWORD: admin
    working_directory: ~/project/build-balance
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Set executable permissions for Gradlew
          command: chmod +x ./gradlew
      - run:
          name: Install Dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
            sudo tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz -C /usr/local/bin
      - run:
          name: Wait for PostgreSQL
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set Spring Profile
          command: echo 'export SPRING_PROFILES_ACTIVE=ci' >> $BASH_ENV
      - run:
          name: Calculate cache key
          command: |
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports

workflows:
  build-and-test:
    jobs:
      - test-java
