version: '3.8'

services:
  postgres:
    image: 'postgres:16'
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-module:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "./scripts/check-db.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: